In [2]:
import pandas as pd
from pathlib import Path

In [11]:
bae_path = '../results_essentials/ag_news/bae3_0/summary.csv'
mango_path = '../results_essentials/ag_news/mango_0/summary.csv'
gbda_path = '../results_essentials/ag_news/gumbel_logits_adam_0/summary.csv'

In [7]:
bae_df = pd.read_csv(bae_path)
bae_df

,Unnamed: 0,original,perturbed,result,result_summary,bert_f1
0,0,india warns u. s. on arms sales to pakistan w...,india warns u. s. on arms deal to pakistan wa...,0 (100%) --> 2 (54%),OK,0.96
1,1,"wto rules against us, eu on sugar, cotton lat...","wto demonstration against slavery, eu on suga...",2 (100%) --> 0 (50%),OK,0.89
2,2,braves'thomson leaves game 3 ( ap ) ap - atla...,braves'analyst post preseason two ( preseason...,1 (100%) --> [FAILED],FAILED,0.67
3,3,2 more turkish men taken hostage in iraq ( ap...,2 more turkish men abducted students in ap ( ...,0 (100%) --> 3 (92%),OK,0.83
4,4,manmohan arrives in manipur imphal : prime mi...,manmohan arrives in manipur imphal : revenue ...,0 (100%) --> 2 (81%),OK,0.98
...,...,...,...,...,...,...
995,995,intel beats expectations but warns on invento...,intel beats chrysler but tops on inventory dr...,3 (92%) --> 2 (55%),OK,0.87
996,996,eds picks siebel as its preferred crm vendor ...,eds picks siebel as its preferred crm vendor ...,2 (73%) --> [SKIPPED],SKIPPED,1.00
997,997,"federer drawn with hewitt, roddick up against...","federer signed with england, usa plays agains...",1 (100%) --> [FAILED],FAILED,0.58
998,998,a gusher of cash for domestic drilling while ...,a gusher of cash for domestic drilling for th...,2 (100%) --> 3 (83%),OK,0.90
999,999,"erickson cites mistakes, but backs rattay aft...","erickson cited mistakes, but came running aft...",1 (100%) --> 0 (51%),OK,0.72

In [8]:
mango_df = pd.read_csv(mango_path)
mango_df

,Unnamed: 0,original,perturbed,result,result_summary,bert_f1
0,0,india warns u. s. on arms sales to pakistan w...,india warns u. s. on missile threats to come ...,0 (100%) --> 2 (100%),OK,0.87
1,1,"wto rules against us, eu on sugar, cotton lat...","# # to 1871 rules against us, eu, sugar, cott...",2 (100%) --> 0 (97%),OK,0.82
2,2,braves'thomson leaves game 3 ( ap ) ap - atla...,braves'ann leaves leg 3 ( ap ) pre - 3 braves...,1 (100%) --> 3 (98%),OK,0.76
3,3,2 more turkish men taken hostage in iraq ( ap...,2 more turkish men taken hostage in iraq ( ap...,0 (100%) --> [FAILED],FAILED,0.96
4,4,manmohan arrives in manipur imphal : prime mi...,manmohan arrives in manipur imphal : prime mi...,0 (100%) --> 2 (97%),OK,0.85
...,...,...,...,...,...,...
995,995,intel beats expectations but warns on invento...,intel beats expectations but warns on invento...,3 (92%) --> 2 (99%),OK,0.82
996,996,eds picks siebel as its preferred crm vendor ...,eds picks siebel as its preferred crm vendor ...,2 (73%) --> [SKIPPED],SKIPPED,1.00
997,997,"federer drawn with hewitt, roddick up against...","federer drawn level hewitt, roddick up agains...",1 (100%) --> 3 (99%),OK,0.74
998,998,a gusher of cash for domestic drilling while ...,a damsher of cash for domestic exploration wh...,2 (100%) --> 3 (100%),OK,0.87
999,999,"erickson cites mistakes, but backs rattay aft...","erickson cites mistakes, but tackles benchtay...",1 (100%) --> 0 (100%),OK,0.74

In [12]:
gbda_df = pd.read_csv(gbda_path)
gbda_df

,Unnamed: 0,original,perturbed,result,result_summary,bert_f1
0,0,india warns u. s. on arms sales to pakistan w...,india warns u. s. on arms sales to america wa...,0 (100%) --> 2 (100%),OK,0.91
1,1,"wto rules against us, eu on sugar, cotton lat...","wmp rules against us, eu on sugar, cotton lat...",2 (100%) --> 1 (96%),OK,0.90
2,2,braves'thomson leaves game 3 ( ap ) ap - atla...,freshmenoredores leaves field 0 braves ap )? ...,1 (100%) --> [FAILED],FAILED,0.63
3,3,2 more turkish men taken hostage in iraq ( ap...,2 more spartan men taken arrested against yes...,0 (100%) --> 1 (100%),OK,0.76
4,4,manmohan arrives in manipur imphal : prime mi...,manmohan arrives in manipur imphal compensati...,0 (100%) --> 2 (96%),OK,0.89
...,...,...,...,...,...,...
995,995,intel beats expectations but warns on invento...,intel beats expectations but warns on invento...,3 (92%) --> 2 (99%),OK,0.86
996,996,eds picks siebel as its preferred crm vendor ...,eds picks siebel as its preferred crm vendor ...,2 (73%) --> [SKIPPED],SKIPPED,1.00
997,997,"federer drawn with hewitt, roddick up against...",federer drawnhoff model. roddick up against s...,1 (100%) --> 3 (82%),OK,0.61
998,998,a gusher of cash for domestic drilling while ...,a gusher of money demanding domestic drilling...,2 (100%) --> 3 (94%),OK,0.88
999,999,"erickson cites mistakes, but backs rattay aft...",eric quarries cites saul solution but backs r...,1 (100%) --> 2 (69%),OK,0.61

In [13]:
def condition_mask(df):
    return (df['result_summary'] == 'OK') & (df['bert_f1'] > 0.9)

mask = condition_mask(bae_df) & condition_mask(mango_df) & condition_mask(gbda_df)
bae_df = bae_df[mask]
mango_df = mango_df[mask]
gbda_df = gbda_df[mask]

/tmp/ipykernel_135116/1417626660.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  bae_df = bae_df[mask]
/tmp/ipykernel_135116/1417626660.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  mango_df = mango_df[mask]

In [19]:
bae_df.sample(2, random_state=0).to_csv('bae_samples.csv')
mango_df.sample(2, random_state=0).to_csv('mango_samples.csv')
gbda_df.sample(2, random_state=0).to_csv('gbda_samples.csv')